# Generated by Django 5.2.1 on 2025-12-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EchoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
                ('maze_data', models.JSONField(default=dict)),
                ('player_pos', models.JSONField(default=lambda: [1, 1])),
                ('echoes', models.JSONField(default=list)),
                ('level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=20)),
                ('original_pos', models.JSONField()),
                ('echo_pos', models.JSONField()),
                ('personality', models.CharField(choices=[('chaotic', 'Chaotic'), ('helpful', 'Helpful'), ('mirror', 'Mirror'), ('delayed', 'Delayed')], max_length=20)),
                ('replay_time', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.echogame')),
            ],
        ),
    ]
